name: war-in-dockertomcat

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 
    
  workflow_dispatch:
  
# 1 workflow se co nhieu task duoc chay tuan tu hoac song song
jobs:
  build:

    runs-on: ubuntu-latest

    #c cac nhiem vu se duoc chay

    steps:
    # pull code tu resposiroty ve may ao centos-latest
    - uses: actions/checkout@v2  

    # ten cua task
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with: 
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven
    - name: Build with maven
      run: mvn clean package



  
