name: war-in-dockertomcat

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 
    
  workflow_dispatch:
  
# 1 workflow se co nhieu task duoc chay tuan tu hoac song song
jobs:
  build:

    runs-on: ubuntu-latest

    #cac cac nhiem vu se duoc chay
    steps:
    # pull code tu resposiroty ve may ao centos-latest
    - uses: actions/checkout@v2 

    # ten cua task
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with maven
      run: mvn clean package

    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        passwork: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      id: docker_build
      with: 
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/loginapptomcat







  
