name: war-in-dockertomcat

on:
  push:
    branches: [ main ]
#   pull:
#     branches: [ main ] 
    
  # workflow_dispatch:
  
# 1 workflow se co nhieu task duoc chay tuan tu hoac song song
jobs:
  build:

    runs-on: ubuntu-latest

    # cac task se duoc chay
    steps:
    # pull code tu resposiroty ve may ao centos-latest
    - uses: actions/checkout@v2 

    # task cai dat java 11
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    # task build project bang maven
    - name: Build with maven
      run: mvn clean package

    # task login docker
    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    
    # task cai dat va su dung buildx 
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
  
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
      
    # task build images va push len dockerhub
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      id: docker_build
      with: 
        # folder chay docker build
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        # build xong push
        push: true
        # danh tag image
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/loginapptomcat:${{ steps.date.outputs.date }}







  
